
# Spring Configuration
server:
  port: 8680
  servlet:
    context-path: ${BILLING_PREFIX:/}

spring:
  application:
    name: subscriptions-management

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/myrealm

# Logging Configuration
logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}
    org.apache.coyote.http11: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring Boot Actuator
management:
  server:
    port: 9006
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: never
  health:
    probes:
      enabled: true

#TMF API Configuration
tmforumapi:
  tmf_endpoint: ${TMF_ENDPOINT:https://tmf.dome-marketplace-sbx.org}
  tmf_envoy:  ${TMF_ENVOY:true}
  # valid only if envoy false
  tmf_namespace:  ${TMF_NAMESPACE:marketplace}
  tmf_postfix:  ${TMF_POSTFIX:svc.cluster.local}
  tmf_port:  ${TMF_PORT:8080}
  # tmf endpoints
  tmf620_product_catalog_management_path: tmf-api/productCatalogManagement/v4
  tmf632_party_management_path: tmf-api/party/v4
  tmf637_inventory_path: tmf-api/productInventory/v4
  tmf666_account_management_path: tmf-api/accountManagement/v4

bae:
  bae_endpoint: ${BAE_ENDPOINT:https://dome-marketplace-sbx.org}

subscription:
  max_active_subscriptions: ${MAX_ACTIVE_SUBSCRIPTIONS:1}